### ISSUE TITLE
Failed "Share to Reels" for just installed Facebook app.

### ISSUE THREAD

**Issue by kimhc999** [fbsamples/share_to_reels_android#7]
Run Share to Reels does not work properly after install Facebook app.
It reproduce on all devices I have tested.
Pixel 6 (Android 12), Pixel 5 (Android 11), Redmi Note 11 (Android 11), Galaxy A12 (Android 11).

But this error does not happen if I install Facebook app and login and wait for some minutes and run it.

https://user-images.githubusercontent.com/3895597/171543891-793f4c37-a4d4-4da7-9338-f5ffdd27f7f2.mp4

**Comment by anujs3** [comment]
> Run Share to Reels does not work properly after install Facebook app. It reproduce on all devices I have tested. Pixel 6 (Android 12), Pixel 5 (Android 11), Redmi Note 11 (Android 11), Galaxy A12 (Android 11).
> 
> But this error does not happen if I install Facebook app and login and wait for some minutes and run it.
> 
>  device-2022-06-02-120047.mp4

Hey @kimhc999, thanks for contacting us about this! Did you see any errors in your logs when you encountered this? Also, did you replace the strings in `app/src/main/res/values/strings.xml` with your Facebook app ID and client token? The buttons won't work until you update those strings.

**Comment by kimhc999** [comment]
Thank you for your response, @anujs3  .
Yes, I also set facebook_app_id and facebook_client_token in string.xml .
When this error occur, the method `activity.getPackageManager().resolveActivity(intent, 0)` returns null.
I have not found any logs.

There is some scenarios how I meet this error.

1. Uninstall Facebook app.
2. Install Facebook app.
3. Try Share to Reels from Sample app. -> Cannot launch Facebook App.
---
1. Uninstall Facebook app.
2. Install Facebook app.
3. Login from Facebook app.
4. Try Share to Reels from Sample app. -> Cannot launch Facebook App.
---
1. Uninstall Facebook app.
2. Install Facebook app.
3. Login from Facebook app.
4. Wait for some minutes
5. Try Share to Reels from Sample app. -> In this case, I can launch Facebook App. I should wait for some minutes.

**Comment by kimhc999** [comment]
I also wrote this issue on "Meta for Developers".
[https://developers.facebook.com/support/bugs/511763073981029/](https://developers.facebook.com/support/bugs/511763073981029/) 
And this issue is resolved by internal team.

Latest version Facebook app does not have this error.
Thank you!
